default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: root
  password: r00t
  pool: 5

development:
  <<: *default
  database: gitfetcher-dev

test:
  <<: *default
  database: gitfetcher-test